version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: citylink
      MYSQL_DATABASE: aayushDB
    ports:
      - "3307:3306"
    restart: always
  nginx: 
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "3050:80"
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: './server'
    ports:
      - "5000:5000"
    volumes:
      - app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './client'
    ports:
      - "3000:3000"
    volumes:
      - app/node_modules
      - ./client:/app